services:
  undf.form.type.image_upload:
    class: Undf\FormBundle\Form\ImageUploadType
    arguments:
      - "@vich_uploader.templating.helper.uploader_helper"
      - "@validator"
      - "@doctrine"
      - "@property_accessor"
    tags:
      - { name: form.type, alias: image_upload }

  undf.form.type.image_upload_listener:
      class: Undf\FormBundle\Listener\ImageUploadListener
      arguments:
        - "@validator"
        - "@doctrine.orm.default_entity_manager"
        - "@property_accessor"
