services:
  undf.form.type.image_upload:
    class: Undf\FormBundle\Form\ImageUploadType
    arguments:
      - "@vich_uploader.templating.helper.uploader_helper"
      - "@validator"
      - "@doctrine"
      - "@property_accessor"
    tags:
      - { name: form.type, alias: image_upload }
